[build]
  # The directory to deploy
  publish = "dist"
  # The command to build your site
  command = "npm run build"

[context.production.environment]
  # Optional environment variables
  NODE_ENV = "production"
